networks:
  default:
    name: matomo

volumes:
  matomo-data:
  matomo-mysql-data:

services:
  matomo:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MATOMO_DATABASE_ADAPTER: ${MATOMO_DATABASE_ADAPTER}
    ports:
      - ${WEB_PORT}:80
    volumes:
      - matomo-data:/var/www/html
      - ./storage/cron.log:/var/log/cron.log:rw
    entrypoint:
      [
        "/data/docker/wait-for-it.sh",
        "mysql:3306",
        "--",
        "/data/docker/entrypoint.sh",
      ]
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: >
      --max_connections=${MYSQL_MAX_CONNECTIONS}
      --sql_mode=${MYSQL_SQL_MODE}
      --autocommit=${MYSQL_AUTOCOMMIT}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_MAX_CONNECTIONS: ${MYSQL_MAX_CONNECTIONS}
    expose:
      - ${MYSQL_PORT}
    volumes:
      - matomo-mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_PORT: ${PMA_PORT}
      UPLOAD_LIMIT: ${PMA_UPLOAD_LIMIT}
      PMA_ARBITRARY: ${PMA_ARBITRARY}
      MAX_EXECUTION_TIME: ${PMA_MAX_EXECUTION_TIME}
    ports:
      - ${PMA_PORT}:80
    depends_on:
      - mysql
